# Generated by Django 5.2.12 on 2026-09-23 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_donations', '0007_migrate_pending_donations_to_pledge'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pledge',
            new_name='project_don_outside_c38b1e_idx',
            old_name='project_don_outside_ac1234_idx',
        ),
        migrations.RenameIndex(
            model_name='pledge',
            new_name='project_don_donatio_456074_idx',
            old_name='project_don_donatio_ab5678_idx',
        ),
    ]
